export const REGISTER = 'REGISTER';
export const EMAIL_AND_PASSWORD_LOGIN = 'EMAIL_AND_PASSWORD_LOGIN';
export const USER_BOARD = 'USER_BOARD';
export const FIND_ONE_USER = 'FIND_ONE_USER';
export const UPDATE_CART_FOR_USER = 'UPDATE_CART_FOR_USER';

