export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CATEGORY_BOARD = 'CATEGORY_BOARD';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const SUB_CATEGORY_BOARD = 'SUB_CATEGORY_BOARD';

export const PRODUCT_BOARD = 'PRODUCT_BOARD';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const PRODUCT_FOR_CART = 'PRODUCT_FOR_CART';
export const PRODUCT_FOR_CATEGORY = 'PRODUCT_FOR_CATEGORY';

