export const PREPARE_PAYMENT = 'PREPARE_PAYMENT';
export const CHECK_PAYMENT_STATUS = 'CHECK_PAYMENT_STATUS';

export const CREATE_STRIPE = 'CREATE_STRIPE';

export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const FIND_TRANSACTION = 'FIND_TRANSACTION';

export const CREATE_ORDER = 'CREATE_ORDER';